/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectMemberResponseDto } from '../../models/project-member-response-dto';

export interface ProjectMembersControllerFindAll$Params {
  projectId: number;
}

export function projectMembersControllerFindAll(http: HttpClient, rootUrl: string, params: ProjectMembersControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectMemberResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, projectMembersControllerFindAll.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProjectMemberResponseDto>>;
    })
  );
}

projectMembersControllerFindAll.PATH = '/projects/{projectId}/members';
