/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectMemberResponseDto } from '../../models/project-member-response-dto';

export interface ProjectMembersControllerRemove$Params {
  projectId: number;
  userId: number;
}

export function projectMembersControllerRemove(http: HttpClient, rootUrl: string, params: ProjectMembersControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectMemberResponseDto>> {
  const rb = new RequestBuilder(rootUrl, projectMembersControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectMemberResponseDto>;
    })
  );
}

projectMembersControllerRemove.PATH = '/projects/{projectId}/members/{userId}';
