/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IssueResponseDto } from '../../models/issue-response-dto';

export interface IssuesControllerRemove$Params {
  id: number;
}

export function issuesControllerRemove(http: HttpClient, rootUrl: string, params: IssuesControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, issuesControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IssueResponseDto>>;
    })
  );
}

issuesControllerRemove.PATH = '/issues/{id}';
