/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IssueResponseDto } from '../../models/issue-response-dto';

export interface IssuesControllerFindAllFiltered$Params {
  search?: string;
  projectId?: number;
  assigneeId?: number;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  labelId?: number;
}

export function issuesControllerFindAllFiltered(http: HttpClient, rootUrl: string, params?: IssuesControllerFindAllFiltered$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, issuesControllerFindAllFiltered.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('projectId', params.projectId, {});
    rb.query('assigneeId', params.assigneeId, {});
    rb.query('priority', params.priority, {});
    rb.query('labelId', params.labelId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IssueResponseDto>>;
    })
  );
}

issuesControllerFindAllFiltered.PATH = '/';
