/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateIssueDto } from '../../models/create-issue-dto';

export interface IssuesControllerCreate$Params {
  columnId: number;
      body: CreateIssueDto
}

export function issuesControllerCreate(http: HttpClient, rootUrl: string, params: IssuesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, issuesControllerCreate.PATH, 'post');
  if (params) {
    rb.path('columnId', params.columnId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

issuesControllerCreate.PATH = '/columns/{columnId}/issues';
