/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IssueResponseDto } from '../../models/issue-response-dto';
import { UpdateIssueDto } from '../../models/update-issue-dto';

export interface IssuesControllerUpdate$Params {
  id: number;
      body: UpdateIssueDto
}

export function issuesControllerUpdate(http: HttpClient, rootUrl: string, params: IssuesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, issuesControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<IssueResponseDto>>;
    })
  );
}

issuesControllerUpdate.PATH = '/issues/{id}';
