/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponseDto } from '../../models/comment-response-dto';
import { CreateCommentDto } from '../../models/create-comment-dto';

export interface CommentsControllerCreate$Params {
  issueId: number;
      body: CreateCommentDto
}

export function commentsControllerCreate(http: HttpClient, rootUrl: string, params: CommentsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, commentsControllerCreate.PATH, 'post');
  if (params) {
    rb.path('issueId', params.issueId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponseDto>;
    })
  );
}

commentsControllerCreate.PATH = '/issues/{issueId}/comments';
