/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponseDto } from '../../models/comment-response-dto';

export interface CommentsControllerRemove$Params {
  id: number;
}

export function commentsControllerRemove(http: HttpClient, rootUrl: string, params: CommentsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, commentsControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponseDto>;
    })
  );
}

commentsControllerRemove.PATH = '/comments/{id}';
