/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponseDto } from '../../models/comment-response-dto';
import { UpdateCommentDto } from '../../models/update-comment-dto';

export interface CommentsControllerUpdate$Params {
  id: number;
      body: UpdateCommentDto
}

export function commentsControllerUpdate(http: HttpClient, rootUrl: string, params: CommentsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, commentsControllerUpdate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponseDto>;
    })
  );
}

commentsControllerUpdate.PATH = '/comments/{id}';
