/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLabelDto } from '../../models/create-label-dto';
import { LabelResponseDto } from '../../models/label-response-dto';

export interface LabelsControllerCreate$Params {
      body: CreateLabelDto
}

export function labelsControllerCreate(http: HttpClient, rootUrl: string, params: LabelsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<LabelResponseDto>> {
  const rb = new RequestBuilder(rootUrl, labelsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LabelResponseDto>;
    })
  );
}

labelsControllerCreate.PATH = '/labels';
