/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activitiesControllerFindAll } from '../fn/activities/activities-controller-find-all';
import { ActivitiesControllerFindAll$Params } from '../fn/activities/activities-controller-find-all';
import { activitiesControllerFindOne } from '../fn/activities/activities-controller-find-one';
import { ActivitiesControllerFindOne$Params } from '../fn/activities/activities-controller-find-one';
import { ActivityResponseDto } from '../models/activity-response-dto';

@Injectable({ providedIn: 'root' })
export class ActivitiesApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `activitiesControllerFindAll()` */
  static readonly ActivitiesControllerFindAllPath = '/issues/{issueId}/activity';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activitiesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  activitiesControllerFindAll$Response(params: ActivitiesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivityResponseDto>>> {
    const obs = activitiesControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activitiesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activitiesControllerFindAll(params: ActivitiesControllerFindAll$Params, context?: HttpContext): Observable<Array<ActivityResponseDto>> {
    const resp = this.activitiesControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ActivityResponseDto>>): Array<ActivityResponseDto> => r.body)
    );
  }

  /** Path part for operation `activitiesControllerFindOne()` */
  static readonly ActivitiesControllerFindOnePath = '/activity/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activitiesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  activitiesControllerFindOne$Response(params: ActivitiesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ActivityResponseDto>> {
    const obs = activitiesControllerFindOne(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activitiesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activitiesControllerFindOne(params: ActivitiesControllerFindOne$Params, context?: HttpContext): Observable<ActivityResponseDto> {
    const resp = this.activitiesControllerFindOne$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ActivityResponseDto>): ActivityResponseDto => r.body)
    );
  }

}
