/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BoardColumnResponseDto } from '../models/board-column-response-dto';
import { boardColumnsControllerCreate } from '../fn/board-columns/board-columns-controller-create';
import { BoardColumnsControllerCreate$Params } from '../fn/board-columns/board-columns-controller-create';
import { boardColumnsControllerFindAll } from '../fn/board-columns/board-columns-controller-find-all';
import { BoardColumnsControllerFindAll$Params } from '../fn/board-columns/board-columns-controller-find-all';
import { boardColumnsControllerFindOne } from '../fn/board-columns/board-columns-controller-find-one';
import { BoardColumnsControllerFindOne$Params } from '../fn/board-columns/board-columns-controller-find-one';
import { boardColumnsControllerMove } from '../fn/board-columns/board-columns-controller-move';
import { BoardColumnsControllerMove$Params } from '../fn/board-columns/board-columns-controller-move';
import { boardColumnsControllerRemove } from '../fn/board-columns/board-columns-controller-remove';
import { BoardColumnsControllerRemove$Params } from '../fn/board-columns/board-columns-controller-remove';
import { boardColumnsControllerUpdate } from '../fn/board-columns/board-columns-controller-update';
import { BoardColumnsControllerUpdate$Params } from '../fn/board-columns/board-columns-controller-update';

@Injectable({ providedIn: 'root' })
export class BoardColumnsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `boardColumnsControllerFindAll()` */
  static readonly BoardColumnsControllerFindAllPath = '/boards/{boardId}/columns';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardColumnsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardColumnsControllerFindAll$Response(params: BoardColumnsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BoardColumnResponseDto>>> {
    const obs = boardColumnsControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardColumnsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardColumnsControllerFindAll(params: BoardColumnsControllerFindAll$Params, context?: HttpContext): Observable<Array<BoardColumnResponseDto>> {
    const resp = this.boardColumnsControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<BoardColumnResponseDto>>): Array<BoardColumnResponseDto> => r.body)
    );
  }

  /** Path part for operation `boardColumnsControllerCreate()` */
  static readonly BoardColumnsControllerCreatePath = '/boards/{boardId}/columns';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardColumnsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardColumnsControllerCreate$Response(params: BoardColumnsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardColumnResponseDto>> {
    const obs = boardColumnsControllerCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardColumnsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardColumnsControllerCreate(params: BoardColumnsControllerCreate$Params, context?: HttpContext): Observable<BoardColumnResponseDto> {
    const resp = this.boardColumnsControllerCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardColumnResponseDto>): BoardColumnResponseDto => r.body)
    );
  }

  /** Path part for operation `boardColumnsControllerFindOne()` */
  static readonly BoardColumnsControllerFindOnePath = '/columns/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardColumnsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardColumnsControllerFindOne$Response(params: BoardColumnsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardColumnResponseDto>> {
    const obs = boardColumnsControllerFindOne(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardColumnsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardColumnsControllerFindOne(params: BoardColumnsControllerFindOne$Params, context?: HttpContext): Observable<BoardColumnResponseDto> {
    const resp = this.boardColumnsControllerFindOne$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardColumnResponseDto>): BoardColumnResponseDto => r.body)
    );
  }

  /** Path part for operation `boardColumnsControllerUpdate()` */
  static readonly BoardColumnsControllerUpdatePath = '/columns/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardColumnsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardColumnsControllerUpdate$Response(params: BoardColumnsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardColumnResponseDto>> {
    const obs = boardColumnsControllerUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardColumnsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardColumnsControllerUpdate(params: BoardColumnsControllerUpdate$Params, context?: HttpContext): Observable<BoardColumnResponseDto> {
    const resp = this.boardColumnsControllerUpdate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardColumnResponseDto>): BoardColumnResponseDto => r.body)
    );
  }

  /** Path part for operation `boardColumnsControllerRemove()` */
  static readonly BoardColumnsControllerRemovePath = '/columns/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardColumnsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardColumnsControllerRemove$Response(params: BoardColumnsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardColumnResponseDto>> {
    const obs = boardColumnsControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardColumnsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardColumnsControllerRemove(params: BoardColumnsControllerRemove$Params, context?: HttpContext): Observable<BoardColumnResponseDto> {
    const resp = this.boardColumnsControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardColumnResponseDto>): BoardColumnResponseDto => r.body)
    );
  }

  /** Path part for operation `boardColumnsControllerMove()` */
  static readonly BoardColumnsControllerMovePath = '/columns/{id}/position';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardColumnsControllerMove()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardColumnsControllerMove$Response(params: BoardColumnsControllerMove$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardColumnResponseDto>> {
    const obs = boardColumnsControllerMove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardColumnsControllerMove$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardColumnsControllerMove(params: BoardColumnsControllerMove$Params, context?: HttpContext): Observable<BoardColumnResponseDto> {
    const resp = this.boardColumnsControllerMove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardColumnResponseDto>): BoardColumnResponseDto => r.body)
    );
  }

}
