/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BoardResponseDto } from '../models/board-response-dto';
import { boardsControllerCreate } from '../fn/boards/boards-controller-create';
import { BoardsControllerCreate$Params } from '../fn/boards/boards-controller-create';
import { boardsControllerFindAll } from '../fn/boards/boards-controller-find-all';
import { BoardsControllerFindAll$Params } from '../fn/boards/boards-controller-find-all';
import { boardsControllerFindOne } from '../fn/boards/boards-controller-find-one';
import { BoardsControllerFindOne$Params } from '../fn/boards/boards-controller-find-one';
import { boardsControllerRemove } from '../fn/boards/boards-controller-remove';
import { BoardsControllerRemove$Params } from '../fn/boards/boards-controller-remove';
import { boardsControllerUpdate } from '../fn/boards/boards-controller-update';
import { BoardsControllerUpdate$Params } from '../fn/boards/boards-controller-update';

@Injectable({ providedIn: 'root' })
export class BoardsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `boardsControllerFindAll()` */
  static readonly BoardsControllerFindAllPath = '/projects/{projectId}/boards';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardsControllerFindAll$Response(params: BoardsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BoardResponseDto>>> {
    const obs = boardsControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardsControllerFindAll(params: BoardsControllerFindAll$Params, context?: HttpContext): Observable<Array<BoardResponseDto>> {
    const resp = this.boardsControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<BoardResponseDto>>): Array<BoardResponseDto> => r.body)
    );
  }

  /** Path part for operation `boardsControllerCreate()` */
  static readonly BoardsControllerCreatePath = '/projects/{projectId}/boards';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardsControllerCreate$Response(params: BoardsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardResponseDto>> {
    const obs = boardsControllerCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardsControllerCreate(params: BoardsControllerCreate$Params, context?: HttpContext): Observable<BoardResponseDto> {
    const resp = this.boardsControllerCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardResponseDto>): BoardResponseDto => r.body)
    );
  }

  /** Path part for operation `boardsControllerFindOne()` */
  static readonly BoardsControllerFindOnePath = '/boards/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardsControllerFindOne$Response(params: BoardsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardResponseDto>> {
    const obs = boardsControllerFindOne(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardsControllerFindOne(params: BoardsControllerFindOne$Params, context?: HttpContext): Observable<BoardResponseDto> {
    const resp = this.boardsControllerFindOne$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardResponseDto>): BoardResponseDto => r.body)
    );
  }

  /** Path part for operation `boardsControllerUpdate()` */
  static readonly BoardsControllerUpdatePath = '/boards/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardsControllerUpdate$Response(params: BoardsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardResponseDto>> {
    const obs = boardsControllerUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  boardsControllerUpdate(params: BoardsControllerUpdate$Params, context?: HttpContext): Observable<BoardResponseDto> {
    const resp = this.boardsControllerUpdate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardResponseDto>): BoardResponseDto => r.body)
    );
  }

  /** Path part for operation `boardsControllerRemove()` */
  static readonly BoardsControllerRemovePath = '/boards/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `boardsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardsControllerRemove$Response(params: BoardsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardResponseDto>> {
    const obs = boardsControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `boardsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  boardsControllerRemove(params: BoardsControllerRemove$Params, context?: HttpContext): Observable<BoardResponseDto> {
    const resp = this.boardsControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BoardResponseDto>): BoardResponseDto => r.body)
    );
  }

}
