/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CommentResponseDto } from '../models/comment-response-dto';
import { commentsControllerCreate } from '../fn/comments/comments-controller-create';
import { CommentsControllerCreate$Params } from '../fn/comments/comments-controller-create';
import { commentsControllerFindAll } from '../fn/comments/comments-controller-find-all';
import { CommentsControllerFindAll$Params } from '../fn/comments/comments-controller-find-all';
import { commentsControllerFindOne } from '../fn/comments/comments-controller-find-one';
import { CommentsControllerFindOne$Params } from '../fn/comments/comments-controller-find-one';
import { commentsControllerRemove } from '../fn/comments/comments-controller-remove';
import { CommentsControllerRemove$Params } from '../fn/comments/comments-controller-remove';
import { commentsControllerUpdate } from '../fn/comments/comments-controller-update';
import { CommentsControllerUpdate$Params } from '../fn/comments/comments-controller-update';

@Injectable({ providedIn: 'root' })
export class CommentsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `commentsControllerFindAll()` */
  static readonly CommentsControllerFindAllPath = '/issues/{issueId}/comments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `commentsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  commentsControllerFindAll$Response(params: CommentsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentResponseDto>>> {
    const obs = commentsControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `commentsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  commentsControllerFindAll(params: CommentsControllerFindAll$Params, context?: HttpContext): Observable<Array<CommentResponseDto>> {
    const resp = this.commentsControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<CommentResponseDto>>): Array<CommentResponseDto> => r.body)
    );
  }

  /** Path part for operation `commentsControllerCreate()` */
  static readonly CommentsControllerCreatePath = '/issues/{issueId}/comments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `commentsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  commentsControllerCreate$Response(params: CommentsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
    const obs = commentsControllerCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `commentsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  commentsControllerCreate(params: CommentsControllerCreate$Params, context?: HttpContext): Observable<CommentResponseDto> {
    const resp = this.commentsControllerCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CommentResponseDto>): CommentResponseDto => r.body)
    );
  }

  /** Path part for operation `commentsControllerFindOne()` */
  static readonly CommentsControllerFindOnePath = '/comments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `commentsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  commentsControllerFindOne$Response(params: CommentsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
    const obs = commentsControllerFindOne(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `commentsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  commentsControllerFindOne(params: CommentsControllerFindOne$Params, context?: HttpContext): Observable<CommentResponseDto> {
    const resp = this.commentsControllerFindOne$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CommentResponseDto>): CommentResponseDto => r.body)
    );
  }

  /** Path part for operation `commentsControllerUpdate()` */
  static readonly CommentsControllerUpdatePath = '/comments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `commentsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  commentsControllerUpdate$Response(params: CommentsControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
    const obs = commentsControllerUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `commentsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  commentsControllerUpdate(params: CommentsControllerUpdate$Params, context?: HttpContext): Observable<CommentResponseDto> {
    const resp = this.commentsControllerUpdate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CommentResponseDto>): CommentResponseDto => r.body)
    );
  }

  /** Path part for operation `commentsControllerRemove()` */
  static readonly CommentsControllerRemovePath = '/comments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `commentsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  commentsControllerRemove$Response(params: CommentsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponseDto>> {
    const obs = commentsControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `commentsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  commentsControllerRemove(params: CommentsControllerRemove$Params, context?: HttpContext): Observable<CommentResponseDto> {
    const resp = this.commentsControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CommentResponseDto>): CommentResponseDto => r.body)
    );
  }

}
