/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { issueLabelsControllerAddLabel } from '../fn/issue-labels/issue-labels-controller-add-label';
import { IssueLabelsControllerAddLabel$Params } from '../fn/issue-labels/issue-labels-controller-add-label';
import { issueLabelsControllerRemoveLabel } from '../fn/issue-labels/issue-labels-controller-remove-label';
import { IssueLabelsControllerRemoveLabel$Params } from '../fn/issue-labels/issue-labels-controller-remove-label';
import { LabelResponseDto } from '../models/label-response-dto';

@Injectable({ providedIn: 'root' })
export class IssueLabelsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `issueLabelsControllerAddLabel()` */
  static readonly IssueLabelsControllerAddLabelPath = '/issue-labels/issues/{issueId}/labels/{labelId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issueLabelsControllerAddLabel()` instead.
   *
   * This method doesn't expect any request body.
   */
  issueLabelsControllerAddLabel$Response(params: IssueLabelsControllerAddLabel$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LabelResponseDto>>> {
    const obs = issueLabelsControllerAddLabel(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issueLabelsControllerAddLabel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issueLabelsControllerAddLabel(params: IssueLabelsControllerAddLabel$Params, context?: HttpContext): Observable<Array<LabelResponseDto>> {
    const resp = this.issueLabelsControllerAddLabel$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<LabelResponseDto>>): Array<LabelResponseDto> => r.body)
    );
  }

  /** Path part for operation `issueLabelsControllerRemoveLabel()` */
  static readonly IssueLabelsControllerRemoveLabelPath = '/issue-labels/issues/{issueId}/labels/{labelId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issueLabelsControllerRemoveLabel()` instead.
   *
   * This method doesn't expect any request body.
   */
  issueLabelsControllerRemoveLabel$Response(params: IssueLabelsControllerRemoveLabel$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LabelResponseDto>>> {
    const obs = issueLabelsControllerRemoveLabel(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issueLabelsControllerRemoveLabel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issueLabelsControllerRemoveLabel(params: IssueLabelsControllerRemoveLabel$Params, context?: HttpContext): Observable<Array<LabelResponseDto>> {
    const resp = this.issueLabelsControllerRemoveLabel$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<LabelResponseDto>>): Array<LabelResponseDto> => r.body)
    );
  }

}
