/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { IssueResponseDto } from '../models/issue-response-dto';
import { issuesControllerAssign } from '../fn/issues/issues-controller-assign';
import { IssuesControllerAssign$Params } from '../fn/issues/issues-controller-assign';
import { issuesControllerCreate } from '../fn/issues/issues-controller-create';
import { IssuesControllerCreate$Params } from '../fn/issues/issues-controller-create';
import { issuesControllerFindAll } from '../fn/issues/issues-controller-find-all';
import { IssuesControllerFindAll$Params } from '../fn/issues/issues-controller-find-all';
import { issuesControllerFindAllFiltered } from '../fn/issues/issues-controller-find-all-filtered';
import { IssuesControllerFindAllFiltered$Params } from '../fn/issues/issues-controller-find-all-filtered';
import { issuesControllerFindLabels } from '../fn/issues/issues-controller-find-labels';
import { IssuesControllerFindLabels$Params } from '../fn/issues/issues-controller-find-labels';
import { issuesControllerFindOne } from '../fn/issues/issues-controller-find-one';
import { IssuesControllerFindOne$Params } from '../fn/issues/issues-controller-find-one';
import { issuesControllerMove } from '../fn/issues/issues-controller-move';
import { IssuesControllerMove$Params } from '../fn/issues/issues-controller-move';
import { issuesControllerRemove } from '../fn/issues/issues-controller-remove';
import { IssuesControllerRemove$Params } from '../fn/issues/issues-controller-remove';
import { issuesControllerUpdate } from '../fn/issues/issues-controller-update';
import { IssuesControllerUpdate$Params } from '../fn/issues/issues-controller-update';
import { issuesControllerUpdatePriority } from '../fn/issues/issues-controller-update-priority';
import { IssuesControllerUpdatePriority$Params } from '../fn/issues/issues-controller-update-priority';
import { LabelResponseDto } from '../models/label-response-dto';

@Injectable({ providedIn: 'root' })
export class IssuesApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `issuesControllerFindAll()` */
  static readonly IssuesControllerFindAllPath = '/columns/{columnId}/issues';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindAll$Response(params: IssuesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindAll(params: IssuesControllerFindAll$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerCreate()` */
  static readonly IssuesControllerCreatePath = '/columns/{columnId}/issues';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerCreate$Response(params: IssuesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = issuesControllerCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerCreate(params: IssuesControllerCreate$Params, context?: HttpContext): Observable<void> {
    const resp = this.issuesControllerCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `issuesControllerFindOne()` */
  static readonly IssuesControllerFindOnePath = '/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindOne$Response(params: IssuesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<IssueResponseDto>> {
    const obs = issuesControllerFindOne(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindOne(params: IssuesControllerFindOne$Params, context?: HttpContext): Observable<IssueResponseDto> {
    const resp = this.issuesControllerFindOne$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<IssueResponseDto>): IssueResponseDto => r.body)
    );
  }

  /** Path part for operation `issuesControllerUpdate()` */
  static readonly IssuesControllerUpdatePath = '/issues/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerUpdate$Response(params: IssuesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerUpdate(params: IssuesControllerUpdate$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerUpdate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerRemove()` */
  static readonly IssuesControllerRemovePath = '/issues/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerRemove$Response(params: IssuesControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerRemove(params: IssuesControllerRemove$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerMove()` */
  static readonly IssuesControllerMovePath = '/issues/{id}/move';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerMove()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerMove$Response(params: IssuesControllerMove$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerMove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerMove$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerMove(params: IssuesControllerMove$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerMove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerAssign()` */
  static readonly IssuesControllerAssignPath = '/issues/{id}/assign';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerAssign()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerAssign$Response(params: IssuesControllerAssign$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerAssign(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerAssign$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerAssign(params: IssuesControllerAssign$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerAssign$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerUpdatePriority()` */
  static readonly IssuesControllerUpdatePriorityPath = '/issues/{id}/priority';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerUpdatePriority()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerUpdatePriority$Response(params: IssuesControllerUpdatePriority$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerUpdatePriority(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerUpdatePriority$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  issuesControllerUpdatePriority(params: IssuesControllerUpdatePriority$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerUpdatePriority$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerFindLabels()` */
  static readonly IssuesControllerFindLabelsPath = '/{id}/labels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerFindLabels()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindLabels$Response(params: IssuesControllerFindLabels$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LabelResponseDto>>> {
    const obs = issuesControllerFindLabels(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerFindLabels$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindLabels(params: IssuesControllerFindLabels$Params, context?: HttpContext): Observable<Array<LabelResponseDto>> {
    const resp = this.issuesControllerFindLabels$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<LabelResponseDto>>): Array<LabelResponseDto> => r.body)
    );
  }

  /** Path part for operation `issuesControllerFindAllFiltered()` */
  static readonly IssuesControllerFindAllFilteredPath = '/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `issuesControllerFindAllFiltered()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindAllFiltered$Response(params?: IssuesControllerFindAllFiltered$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<IssueResponseDto>>> {
    const obs = issuesControllerFindAllFiltered(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `issuesControllerFindAllFiltered$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  issuesControllerFindAllFiltered(params?: IssuesControllerFindAllFiltered$Params, context?: HttpContext): Observable<Array<IssueResponseDto>> {
    const resp = this.issuesControllerFindAllFiltered$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<IssueResponseDto>>): Array<IssueResponseDto> => r.body)
    );
  }

}
