/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { LabelResponseDto } from '../models/label-response-dto';
import { labelsControllerCreate } from '../fn/labels/labels-controller-create';
import { LabelsControllerCreate$Params } from '../fn/labels/labels-controller-create';
import { labelsControllerFindAll } from '../fn/labels/labels-controller-find-all';
import { LabelsControllerFindAll$Params } from '../fn/labels/labels-controller-find-all';
import { labelsControllerRemove } from '../fn/labels/labels-controller-remove';
import { LabelsControllerRemove$Params } from '../fn/labels/labels-controller-remove';

@Injectable({ providedIn: 'root' })
export class LabelsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `labelsControllerFindAll()` */
  static readonly LabelsControllerFindAllPath = '/labels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `labelsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  labelsControllerFindAll$Response(params?: LabelsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = labelsControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `labelsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  labelsControllerFindAll(params?: LabelsControllerFindAll$Params, context?: HttpContext): Observable<void> {
    const resp = this.labelsControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `labelsControllerCreate()` */
  static readonly LabelsControllerCreatePath = '/labels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `labelsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  labelsControllerCreate$Response(params: LabelsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<LabelResponseDto>> {
    const obs = labelsControllerCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `labelsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  labelsControllerCreate(params: LabelsControllerCreate$Params, context?: HttpContext): Observable<LabelResponseDto> {
    const resp = this.labelsControllerCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<LabelResponseDto>): LabelResponseDto => r.body)
    );
  }

  /** Path part for operation `labelsControllerRemove()` */
  static readonly LabelsControllerRemovePath = '/labels/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `labelsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  labelsControllerRemove$Response(params: LabelsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = labelsControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `labelsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  labelsControllerRemove(params: LabelsControllerRemove$Params, context?: HttpContext): Observable<void> {
    const resp = this.labelsControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
