/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { NotificationResponseDto } from '../models/notification-response-dto';
import { notificationsControllerFindAll } from '../fn/notifications/notifications-controller-find-all';
import { NotificationsControllerFindAll$Params } from '../fn/notifications/notifications-controller-find-all';
import { notificationsControllerRead } from '../fn/notifications/notifications-controller-read';
import { NotificationsControllerRead$Params } from '../fn/notifications/notifications-controller-read';
import { notificationsControllerRemove } from '../fn/notifications/notifications-controller-remove';
import { NotificationsControllerRemove$Params } from '../fn/notifications/notifications-controller-remove';

@Injectable({ providedIn: 'root' })
export class NotificationsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationsControllerFindAll()` */
  static readonly NotificationsControllerFindAllPath = '/notifications';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindAll$Response(params?: NotificationsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NotificationResponseDto>>> {
    const obs = notificationsControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerFindAll(params?: NotificationsControllerFindAll$Params, context?: HttpContext): Observable<Array<NotificationResponseDto>> {
    const resp = this.notificationsControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<NotificationResponseDto>>): Array<NotificationResponseDto> => r.body)
    );
  }

  /** Path part for operation `notificationsControllerRead()` */
  static readonly NotificationsControllerReadPath = '/notifications/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRead$Response(params: NotificationsControllerRead$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponseDto>> {
    const obs = notificationsControllerRead(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRead(params: NotificationsControllerRead$Params, context?: HttpContext): Observable<NotificationResponseDto> {
    const resp = this.notificationsControllerRead$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<NotificationResponseDto>): NotificationResponseDto => r.body)
    );
  }

  /** Path part for operation `notificationsControllerRemove()` */
  static readonly NotificationsControllerRemovePath = '/notifications/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRemove$Response(params: NotificationsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponseDto>> {
    const obs = notificationsControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerRemove(params: NotificationsControllerRemove$Params, context?: HttpContext): Observable<NotificationResponseDto> {
    const resp = this.notificationsControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<NotificationResponseDto>): NotificationResponseDto => r.body)
    );
  }

}
