/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ProjectResponseDto } from '../models/project-response-dto';
import { projectsControllerCreate } from '../fn/projects/projects-controller-create';
import { ProjectsControllerCreate$Params } from '../fn/projects/projects-controller-create';
import { projectsControllerFindAll } from '../fn/projects/projects-controller-find-all';
import { ProjectsControllerFindAll$Params } from '../fn/projects/projects-controller-find-all';
import { projectsControllerFindOne } from '../fn/projects/projects-controller-find-one';
import { ProjectsControllerFindOne$Params } from '../fn/projects/projects-controller-find-one';

@Injectable({ providedIn: 'root' })
export class ProjectsApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `projectsControllerFindAll()` */
  static readonly ProjectsControllerFindAllPath = '/projects';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindAll$Response(params?: ProjectsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectResponseDto>>> {
    const obs = projectsControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindAll(params?: ProjectsControllerFindAll$Params, context?: HttpContext): Observable<Array<ProjectResponseDto>> {
    const resp = this.projectsControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ProjectResponseDto>>): Array<ProjectResponseDto> => r.body)
    );
  }

  /** Path part for operation `projectsControllerCreate()` */
  static readonly ProjectsControllerCreatePath = '/projects';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectsControllerCreate$Response(params: ProjectsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = projectsControllerCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectsControllerCreate(params: ProjectsControllerCreate$Params, context?: HttpContext): Observable<void> {
    const resp = this.projectsControllerCreate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `projectsControllerFindOne()` */
  static readonly ProjectsControllerFindOnePath = '/projects/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindOne$Response(params: ProjectsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectResponseDto>> {
    const obs = projectsControllerFindOne(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectsControllerFindOne(params: ProjectsControllerFindOne$Params, context?: HttpContext): Observable<ProjectResponseDto> {
    const resp = this.projectsControllerFindOne$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProjectResponseDto>): ProjectResponseDto => r.body)
    );
  }

}
