/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ProjectMemberResponseDto } from '../models/project-member-response-dto';
import { projectMembersControllerAdd } from '../fn/project-members/project-members-controller-add';
import { ProjectMembersControllerAdd$Params } from '../fn/project-members/project-members-controller-add';
import { projectMembersControllerFindAll } from '../fn/project-members/project-members-controller-find-all';
import { ProjectMembersControllerFindAll$Params } from '../fn/project-members/project-members-controller-find-all';
import { projectMembersControllerRemove } from '../fn/project-members/project-members-controller-remove';
import { ProjectMembersControllerRemove$Params } from '../fn/project-members/project-members-controller-remove';

@Injectable({ providedIn: 'root' })
export class ProjectMembersApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `projectMembersControllerFindAll()` */
  static readonly ProjectMembersControllerFindAllPath = '/projects/{projectId}/members';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectMembersControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectMembersControllerFindAll$Response(params: ProjectMembersControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectMemberResponseDto>>> {
    const obs = projectMembersControllerFindAll(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectMembersControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectMembersControllerFindAll(params: ProjectMembersControllerFindAll$Params, context?: HttpContext): Observable<Array<ProjectMemberResponseDto>> {
    const resp = this.projectMembersControllerFindAll$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ProjectMemberResponseDto>>): Array<ProjectMemberResponseDto> => r.body)
    );
  }

  /** Path part for operation `projectMembersControllerAdd()` */
  static readonly ProjectMembersControllerAddPath = '/projects/{projectId}/members';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectMembersControllerAdd()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectMembersControllerAdd$Response(params: ProjectMembersControllerAdd$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = projectMembersControllerAdd(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectMembersControllerAdd$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectMembersControllerAdd(params: ProjectMembersControllerAdd$Params, context?: HttpContext): Observable<void> {
    const resp = this.projectMembersControllerAdd$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `projectMembersControllerRemove()` */
  static readonly ProjectMembersControllerRemovePath = '/projects/{projectId}/members/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectMembersControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectMembersControllerRemove$Response(params: ProjectMembersControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectMemberResponseDto>> {
    const obs = projectMembersControllerRemove(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectMembersControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectMembersControllerRemove(params: ProjectMembersControllerRemove$Params, context?: HttpContext): Observable<ProjectMemberResponseDto> {
    const resp = this.projectMembersControllerRemove$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProjectMemberResponseDto>): ProjectMemberResponseDto => r.body)
    );
  }

}
