/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { UserResponseDto } from '../models/user-response-dto';
import { usersControllerDelete } from '../fn/users/users-controller-delete';
import { UsersControllerDelete$Params } from '../fn/users/users-controller-delete';
import { usersControllerMe } from '../fn/users/users-controller-me';
import { UsersControllerMe$Params } from '../fn/users/users-controller-me';
import { usersControllerSearch } from '../fn/users/users-controller-search';
import { UsersControllerSearch$Params } from '../fn/users/users-controller-search';
import { usersControllerUpdate } from '../fn/users/users-controller-update';
import { UsersControllerUpdate$Params } from '../fn/users/users-controller-update';

@Injectable({ providedIn: 'root' })
export class UsersApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usersControllerMe()` */
  static readonly UsersControllerMePath = '/users/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerMe$Response(params?: UsersControllerMe$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    const obs = usersControllerMe(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerMe(params?: UsersControllerMe$Params, context?: HttpContext): Observable<UserResponseDto> {
    const resp = this.usersControllerMe$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `usersControllerUpdate()` */
  static readonly UsersControllerUpdatePath = '/users/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerUpdate$Response(params: UsersControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    const obs = usersControllerUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerUpdate(params: UsersControllerUpdate$Params, context?: HttpContext): Observable<UserResponseDto> {
    const resp = this.usersControllerUpdate$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `usersControllerDelete()` */
  static readonly UsersControllerDeletePath = '/users/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerDelete$Response(params?: UsersControllerDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponseDto>> {
    const obs = usersControllerDelete(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerDelete(params?: UsersControllerDelete$Params, context?: HttpContext): Observable<UserResponseDto> {
    const resp = this.usersControllerDelete$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body)
    );
  }

  /** Path part for operation `usersControllerSearch()` */
  static readonly UsersControllerSearchPath = '/users/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerSearch$Response(params: UsersControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserResponseDto>>> {
    const obs = usersControllerSearch(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerSearch(params: UsersControllerSearch$Params, context?: HttpContext): Observable<Array<UserResponseDto>> {
    const resp = this.usersControllerSearch$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<UserResponseDto>>): Array<UserResponseDto> => r.body)
    );
  }

}
