/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationResponseDto } from '../../models/notification-response-dto';

export interface NotificationsControllerRemove$Params {
  id: number;
}

export function notificationsControllerRemove(http: HttpClient, rootUrl: string, params: NotificationsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationResponseDto>;
    })
  );
}

notificationsControllerRemove.PATH = '/notifications/{id}';
