/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BoardColumnResponseDto } from '../../models/board-column-response-dto';

export interface BoardColumnsControllerFindAll$Params {
  boardId: number;
}

export function boardColumnsControllerFindAll(http: HttpClient, rootUrl: string, params: BoardColumnsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BoardColumnResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, boardColumnsControllerFindAll.PATH, 'get');
  if (params) {
    rb.path('boardId', params.boardId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BoardColumnResponseDto>>;
    })
  );
}

boardColumnsControllerFindAll.PATH = '/boards/{boardId}/columns';
