/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BoardColumnResponseDto } from '../../models/board-column-response-dto';
import { MoveColumnDto } from '../../models/move-column-dto';

export interface BoardColumnsControllerMove$Params {
  id: number;
      body: MoveColumnDto
}

export function boardColumnsControllerMove(http: HttpClient, rootUrl: string, params: BoardColumnsControllerMove$Params, context?: HttpContext): Observable<StrictHttpResponse<BoardColumnResponseDto>> {
  const rb = new RequestBuilder(rootUrl, boardColumnsControllerMove.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BoardColumnResponseDto>;
    })
  );
}

boardColumnsControllerMove.PATH = '/columns/{id}/position';
