/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityResponseDto } from '../../models/activity-response-dto';

export interface ActivitiesControllerFindAll$Params {
  issueId: number;
  page?: number;
  limit?: number;
}

export function activitiesControllerFindAll(http: HttpClient, rootUrl: string, params: ActivitiesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivityResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, activitiesControllerFindAll.PATH, 'get');
  if (params) {
    rb.path('issueId', params.issueId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActivityResponseDto>>;
    })
  );
}

activitiesControllerFindAll.PATH = '/issues/{issueId}/activity';
