/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityResponseDto {
  action: 'ISSUE_CREATED' | 'ISSUE_UPDATED' | 'ISSUE_MOVED' | 'ISSUE_ASSIGNED' | 'ISSUE_DELETED' | 'COMMENT_CREATED' | 'COMMENT_UPDATED' | 'COMMENT_DELETED';
  createdAt: string;
  id: number;
  metadata?: {
};
  user: {
};
}
