/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BoardColumnResponseDto {
  boardId: number;
  createdAt: string;
  id: number;
  name: string;
  position: number;
  updatedAt: string;
}
