/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BoardResponseDto {
  createdAt: string;
  id: number;
  name: string;
  projectId: number;
  updatedAt: string;
}
