/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentResponseDto {
  content: string;
  createdAt: string;
  id: number;
  issueId: number;
  updatedAt: string;
  user?: {
};
  userId: number;
}
