/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IssueResponseDto {
  assigneeId?: number;
  boardId: number;
  columnId: number;
  createdAt: string;
  creatorId: number;
  description?: string;
  id: number;
  position: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  projectId: number;
  title: string;
  updatedAt: string;
}
