/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserMemberDto } from '../models/user-member-dto';
export interface ProjectMemberResponseDto {
  createdAt: string;
  id: number;
  projectId: number;
  role: 'OWNER' | 'ADMIN' | 'MEMBER';
  user: UserMemberDto;
  userId: number;
}
