/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectResponseDto {
  createdAt: string;
  description?: string;
  id: number;
  name: string;
  ownerId: number;
  updatedAt: string;
}
