/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LabelResponseDto } from '../../models/label-response-dto';

export interface IssueLabelsControllerRemoveLabel$Params {
  issueId: number;
  labelId: number;
}

export function issueLabelsControllerRemoveLabel(http: HttpClient, rootUrl: string, params: IssueLabelsControllerRemoveLabel$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LabelResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, issueLabelsControllerRemoveLabel.PATH, 'delete');
  if (params) {
    rb.path('issueId', params.issueId, {});
    rb.path('labelId', params.labelId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LabelResponseDto>>;
    })
  );
}

issueLabelsControllerRemoveLabel.PATH = '/issue-labels/issues/{issueId}/labels/{labelId}';
